# [PRACTICA DE NUMPY](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/)
## [Curso Python para Ciencia de datos](https://joserzapata.github.io/courses/python-ciencia-datos/)
### Por Jose R. Zapata - https://joserzapata.github.io/

<div class="alert alert-success">

<b>NOTA:</b> Realizar Primero los ejercicios y luego revisar las soluciones propuestas.

[Solucion Ejercicios Numpy - click para abrir](https://joserzapata.github.io/courses/python-ciencia-datos/numpy/2-practica_numpy-solucion/)

</div>

Los arreglos de numpy son la base de la computación científica en Python
- los dataframes de pandas para análisis de datos (Numpy era la unica base hasta pandas 1.5.3)
- los datos de entrada o salida para hacer Machine Learning con scikit-learn son arreglos de numpy

**Nota:** Es importante familiarizarse con el manejo de arreglos de numpy para poder hacer ciencia de datos con Python e identificar cuando usar un arreglo de numpy o un dataframe de pandas.

**Importe NumPy como np**

In [1]:
import numpy as np

**Cree un arreglo de ceros de 10 elementos**

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Cree un arreglo de unos de 10 elementos**

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Cree un arreglo de cincos de 10 elementos**

In [12]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

**Cree un arreglo de números enteros Del 10 al 50 (incluido)**

In [13]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Cree un arreglo de los números enteros pares Del 10 al 50 (incluidos)**

In [14]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Crear una matrix de 3x3 con valores del 0 al 8 (incluido)**

In [15]:
array = np.arange(0,9)
array.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Crear la matriz identidad de 3x3**

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Use NumPy para generar un numero aleatorio entre 0 y 1**

In [18]:
np.random.rand(1)

array([0.7009608])

array([0.45619523])

**Use NumPy para generar un arreglo de 25 números aleatorios que sean de la distribucion normal estandar**

In [21]:
np.random.randn(25)

array([-1.47444764, -0.26246916,  0.03643534,  4.16355058,  0.28104691,
        0.85929747, -0.01230701, -1.04236506, -1.12474648, -0.21487003,
       -1.38771725, -0.17645859, -1.91683918,  1.20229873, -1.37014077,
        1.77713772,  1.92119153,  0.9999476 , -0.52503372, -0.09310142,
        0.72375469, -0.69820389, -1.46398586, -0.25141947, -1.53198765])

array([-1.82518925,  0.35985968,  0.7908014 ,  1.09115394, -1.18145353,
       -0.38358405, -0.1049287 ,  1.27313964,  0.05365275, -0.63835531,
        0.4984666 , -1.60464831, -0.84688945,  0.4695778 ,  1.73142269,
       -1.63808225, -0.67171648, -0.14015625,  0.50828476,  0.60145966,
       -0.34493194,  0.09632452, -0.85907492, -0.46924336,  1.22406872])

**Cree un arreglo de 20 elementos linealmente espaciados entre 0 y 1:**

In [25]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

**Indexacion y seleccion con Numpy**

Crear una matriz con numeros del 1 al 25 y que tenga forma de 5x5



In [27]:
array = np.arange(1,26)
array.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

replique los resultados que siguen:


In [33]:
pri = np.arange(12,16)
seg = np.arange(17,21)
ter = np.arange(22,26)
np.array([pri,seg,ter])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [40]:
arr = 20
arr

20

20

In [45]:
arr = np.arange(2,13,4)
arr.reshape(3,1)

array([[ 2],
       [ 6],
       [10]])

array([[ 2],
       [ 7],
       [12]])

In [46]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [47]:
ran = np.arange(16,26)
ran.reshape(2,5)


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Obtenga la suma de todos los valores de la matriz**

In [53]:
numero = np.array([300,20,5])
suma = numero.sum()
print(suma)

325


325

**Obtenga la desviación estándar de los valores de la matriz**

In [101]:
array = np.array([[15.8, 19, 30, 33]])
desviacion = array.std()
print(desviacion)

7.218552486475388


7.211102550927978

**Obtener la suma de cada una de las columnas de la matriz**

In [108]:
arr = np.array([[50, 55, 35, 35],[5, 5, 35, 40]])
arr.sum(axis=0)

array([55, 60, 70, 75])

array([55, 60, 65, 70, 75])

## Referencia

https://joserzapata.github.io/courses/python-ciencia-datos/numpy/